//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class abrechnung
    {
        public abrechnung()
        {
            this.position_abrechnung = new HashSet<position_abrechnung>();
            this.zahlung = new HashSet<zahlung>();
        }
    
        public int id_abrechnung { get; set; }
        public string referenz { get; set; }
        public int pod_id_pod { get; set; }
        public int adresse_id_adresse { get; set; }
        public System.DateTime fakturierungsdatum { get; set; }
    
        public virtual pod pod { get; set; }
        public virtual adresse adresse { get; set; }
        public virtual ICollection<position_abrechnung> position_abrechnung { get; set; }
        public virtual ICollection<zahlung> zahlung { get; set; }
    }
}
