//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrativ_credentials_snmp_comunity
    {
        public administrativ_credentials_snmp_comunity()
        {
            this.device = new HashSet<device>();
        }
    
        public int id_administrativ_credentials { get; set; }
        public int administrativ_credentials_id_administrativ_credentials { get; set; }
        public int snmp_comunity_id_snmpcomunity { get; set; }
    
        public virtual administrativ_credentials administrativ_credentials { get; set; }
        public virtual snmp_comunity snmp_comunity { get; set; }
        public virtual ICollection<device> device { get; set; }
    }
}
