//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_typ
    {
        public device_typ()
        {
            this.device = new HashSet<device>();
        }
    
        public int id_device_typ { get; set; }
        public string geraete_typ { get; set; }
        public bool virtuel { get; set; }
        public Nullable<int> hersteller_id_hersteller { get; set; }
        public int geraetebezeichnung_id_geraetebezeichnung { get; set; }
        public Nullable<int> geraetetyp_id_geraetetyp { get; set; }
        public Nullable<decimal> preis { get; set; }
    
        public virtual ICollection<device> device { get; set; }
        public virtual hersteller hersteller { get; set; }
        public virtual geraetebezeichnung geraetebezeichnung { get; set; }
        public virtual geraetetyp geraetetyp { get; set; }
    }
}
