//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.logging = new HashSet<logging>();
            this.netzwerkinterface = new HashSet<netzwerkinterface>();
            this.position_abrechnung = new HashSet<position_abrechnung>();
            this.administrativ_credentials_snmp_comunity = new HashSet<administrativ_credentials_snmp_comunity>();
        }
    
        public int id_device { get; set; }
        public Nullable<int> location_id_location { get; set; }
        public string seriennummer { get; set; }
        public string hostname { get; set; }
        public int device_typ_id_devicetyp { get; set; }
        public Nullable<sbyte> isActive { get; set; }
    
        public virtual location location { get; set; }
        public virtual device_typ device_typ { get; set; }
        public virtual ICollection<logging> logging { get; set; }
        public virtual ICollection<netzwerkinterface> netzwerkinterface { get; set; }
        public virtual ICollection<position_abrechnung> position_abrechnung { get; set; }
        public virtual ICollection<administrativ_credentials_snmp_comunity> administrativ_credentials_snmp_comunity { get; set; }
    }
}
