//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pod
    {
        public pod()
        {
            this.abrechnung = new HashSet<abrechnung>();
            this.location = new HashSet<location>();
            this.pod_person = new HashSet<pod_person>();
        }
    
        public int id_pod { get; set; }
        public string zeitzone { get; set; }
        public int id_kunde { get; set; }
    
        public virtual ICollection<abrechnung> abrechnung { get; set; }
        public virtual kunde kunde { get; set; }
        public virtual ICollection<location> location { get; set; }
        public virtual ICollection<pod_person> pod_person { get; set; }
    }
}
