//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pod_person
    {
        public int pod_id_pod { get; set; }
        public int person_id_person { get; set; }
        public sbyte prioritaet { get; set; }
    
        public virtual person person { get; set; }
        public virtual pod pod { get; set; }
    }
}
