//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_abrechnung
    {
        public int id_position { get; set; }
        public Nullable<int> abrechnung_id_abrechnung { get; set; }
        public string name { get; set; }
        public decimal preis { get; set; }
        public Nullable<int> netzwerkinterface_id_netzwerkinterface { get; set; }
        public Nullable<int> device_id_device { get; set; }
        public int location_id_location { get; set; }
    
        public virtual abrechnung abrechnung { get; set; }
        public virtual device device { get; set; }
        public virtual location location { get; set; }
        public virtual netzwerkinterface netzwerkinterface { get; set; }
    }
}
