//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vlan
    {
        public vlan()
        {
            this.netzwerkinterface = new HashSet<netzwerkinterface>();
        }
    
        public int id_vlan { get; set; }
        public string bezeichnung { get; set; }
        public string net_adress { get; set; }
        public string subnetmask { get; set; }
        public string standart_gateway { get; set; }
        public int location_id_location { get; set; }
    
        public virtual location location { get; set; }
        public virtual ICollection<netzwerkinterface> netzwerkinterface { get; set; }
    }
}
