//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class zahlung
    {
        public zahlung()
        {
            this.abrechnung = new HashSet<abrechnung>();
        }
    
        public int id_zahlung { get; set; }
        public int kunde_id { get; set; }
        public Nullable<decimal> betrag { get; set; }
        public System.DateTime zahlungsdatum { get; set; }
    
        public virtual kunde kunde { get; set; }
        public virtual ICollection<abrechnung> abrechnung { get; set; }
    }
}
