//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class lieferant
    {
        public lieferant()
        {
            this.hersteller = new HashSet<hersteller>();
        }
    
        public int id_lieferant { get; set; }
        public string name { get; set; }
        public int adresse_adresse_id { get; set; }
    
        public virtual adresse adresse { get; set; }
        public virtual ICollection<hersteller> hersteller { get; set; }
    }
}
