//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.device = new HashSet<device>();
            this.position_abrechnung = new HashSet<position_abrechnung>();
            this.vlan = new HashSet<vlan>();
        }
    
        public int id_location { get; set; }
        public string location_name { get; set; }
        public int adresse_id_adresse { get; set; }
        public int pod_id_pod { get; set; }
    
        public virtual adresse adresse { get; set; }
        public virtual ICollection<device> device { get; set; }
        public virtual pod pod { get; set; }
        public virtual ICollection<position_abrechnung> position_abrechnung { get; set; }
        public virtual ICollection<vlan> vlan { get; set; }
    }
}
