//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class netzwerkinterface
    {
        public netzwerkinterface()
        {
            this.netzwerkinterface1 = new HashSet<netzwerkinterface>();
            this.position_abrechnung = new HashSet<position_abrechnung>();
            this.vlan = new HashSet<vlan>();
        }
    
        public int id_netzwerkinterface { get; set; }
        public string name { get; set; }
        public int device_id_device { get; set; }
        public Nullable<bool> fullduplex { get; set; }
        public Nullable<bool> virtuel { get; set; }
        public string mac_adresse { get; set; }
        public Nullable<int> bandbreite_mbit { get; set; }
        public Nullable<int> netzwerkinterface_id_netzwerkinterface { get; set; }
        public string Medium { get; set; }
        public Nullable<int> Portnummer { get; set; }
    
        public virtual device device { get; set; }
        public virtual ICollection<netzwerkinterface> netzwerkinterface1 { get; set; }
        public virtual netzwerkinterface netzwerkinterface2 { get; set; }
        public virtual ICollection<position_abrechnung> position_abrechnung { get; set; }
        public virtual ICollection<vlan> vlan { get; set; }
    }
}
